name=WS281xProcessor
version=0.1.1
author=Juergen Winkler
maintainer=Jueff <mobaledlib@gmx.at>
sentence=Library allows processing of WS2812 protocol
paragraph=
category=Signal Input/Output
url=https://github.com/Jueff/WS281xProcessor#readme
architectures=rp2040
includes=WS281xProcessor.h
depends=
