[platformio]
src_dir = src
    
[env]
framework = arduino
build_src_flags = 

[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
Board = pico
framework = arduino
board_build.core = earlephilhower  