// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// -------------- //
// ws2811Repeater //
// -------------- //

#define ws2811Repeater_wrap_target 0
#define ws2811Repeater_wrap 22

#define ws2811Repeater_offset_wait_sideset_reset 0u
#define ws2811Repeater_offset_num_bits_emulate 4u
#define ws2811Repeater_offset_wait_sideset_bit 16u

static const uint16_t ws2811Repeater_program_instructions[] = {
            //     .wrap_target
    0x209d, //  0: wait   1 gpio, 29                 
    0x00c3, //  1: jmp    pin, 3                     
    0x0000, //  2: jmp    0                          
    0xa026, //  3: mov    x, isr                     
    0xe058, //  4: set    y, 24                      
    0x80a0, //  5: pull   block                      
    0x0028, //  6: jmp    !x, 8                      
    0x0f50, //  7: jmp    x--, 16                [15]
    0x006d, //  8: jmp    !y, 13                     
    0xef01, //  9: set    pins, 1                [15]
    0x7601, // 10: out    pins, 1                [22]
    0xe000, // 11: set    pins, 0                    
    0x0090, // 12: jmp    y--, 16                    
    0xe001, // 13: set    pins, 1                    
    0x2020, // 14: wait   0 pin, 0                   
    0xe000, // 15: set    pins, 0                    
    0x209d, // 16: wait   1 gpio, 29                 
    0x00c6, // 17: jmp    pin, 6                     
    0xa026, // 18: mov    x, isr                     
    0xa0c2, // 19: mov    isr, y                     
    0x8000, // 20: push   noblock                    
    0xa0c1, // 21: mov    isr, x                     
    0x0060, // 22: jmp    !y, 0                      
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program ws2811Repeater_program = {
    .instructions = ws2811Repeater_program_instructions,
    .length = 23,
    .origin = -1,
};

static inline pio_sm_config ws2811Repeater_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + ws2811Repeater_wrap_target, offset + ws2811Repeater_wrap);
    return c;
}
#endif
