// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// -------------- //
// ws2811Receiver //
// -------------- //

#define ws2811Receiver_wrap_target 0
#define ws2811Receiver_wrap 30

#define ws2811Receiver_offset_num_bits_const_1 3u
#define ws2811Receiver_offset_num_bits_shift_1 5u
#define ws2811Receiver_offset_num_bits_const_2 12u
#define ws2811Receiver_offset_num_bits_shift_2 14u

static const uint16_t ws2811Receiver_program_instructions[] = {
            //     .wrap_target
    0xb047, //  0: mov    y, osr          side 0     
    0x10dd, //  1: jmp    pin, 29         side 0     
    0x1081, //  2: jmp    y--, 1          side 0     
    0xf038, //  3: set    x, 24           side 0     
    0xbfc1, //  4: mov    isr, x          side 1 [7] 
    0x5061, //  5: in     null, 1         side 0     
    0xb026, //  6: mov    x, isr          side 0     
    0xb0c3, //  7: mov    isr, null       side 0     
    0x1049, //  8: jmp    x--, 9          side 0     
    0xb047, //  9: mov    y, osr          side 0     
    0x10d5, // 10: jmp    pin, 21         side 0     
    0x108a, // 11: jmp    y--, 10         side 0     
    0xf058, // 12: set    y, 24           side 0     
    0xb0c2, // 13: mov    isr, y          side 0     
    0x5061, // 14: in     null, 1         side 0     
    0xb046, // 15: mov    y, isr          side 0     
    0x1091, // 16: jmp    y--, 17         side 0     
    0x10b3, // 17: jmp    x != y, 19      side 0     
    0x1003, // 18: jmp    3               side 0     
    0xd002, // 19: irq    nowait 2        side 0     
    0x1003, // 20: jmp    3               side 0     
    0xff45, // 21: set    y, 5            side 1 [7] 
    0xb442, // 22: nop                    side 0 [4] 
    0x1396, // 23: jmp    y--, 22         side 0 [3] 
    0x5001, // 24: in     pins, 1         side 0     
    0x3020, // 25: wait   0 pin, 0        side 0     
    0x1049, // 26: jmp    x--, 9          side 0     
    0xd001, // 27: irq    nowait 1        side 0     
    0x1000, // 28: jmp    0               side 0     
    0xbf42, // 29: nop                    side 1 [7] 
    0x3020, // 30: wait   0 pin, 0        side 0     
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program ws2811Receiver_program = {
    .instructions = ws2811Receiver_program_instructions,
    .length = 31,
    .origin = -1,
};

static inline pio_sm_config ws2811Receiver_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + ws2811Receiver_wrap_target, offset + ws2811Receiver_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}
#endif
