// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------------ //
// ws2811Status //
// ------------ //

#define ws2811Status_wrap_target 0
#define ws2811Status_wrap 11

static const uint16_t ws2811Status_program_instructions[] = {
            //     .wrap_target
    0xe038, //  0: set    x, 24                      
    0x80a0, //  1: pull   block                      
    0xef01, //  2: set    pins, 1                [15]
    0x7601, //  3: out    pins, 1                [22]
    0xfe00, //  4: set    pins, 0                [30]
    0x0742, //  5: jmp    x--, 2                 [7] 
    0xe054, //  6: set    y, 20                      
    0xa0e2, //  7: mov    osr, y                     
    0x606a, //  8: out    null, 10                   
    0xa047, //  9: mov    y, osr                     
    0x008a, // 10: jmp    y--, 10                    
    0x0000, // 11: jmp    0                          
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program ws2811Status_program = {
    .instructions = ws2811Status_program_instructions,
    .length = 12,
    .origin = -1,
};

static inline pio_sm_config ws2811Status_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + ws2811Status_wrap_target, offset + ws2811Status_wrap);
    return c;
}
#endif
